version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./webapp:/webapp
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    image: flask-webapp:latest
    build: .
    container_name: gunicorn