version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webapp:/webapp
      - ./nginx:/etc/nginx
    depends_on:
      - web
    networks:
      - reverse-proxy
  web:
    image: flask-webapp:latest
    build: .
    container_name: gunicorn
    ports:
      - "8080:8080"
    networks:
      - reverse-proxy
      - default

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
