version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webapp:/webapp
      - ./nginx:/etc/nginx
    depends_on:
      - web
  web:
    image: flask-webapp:latest
    build: .
    container_name: gunicorn
